# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [9]:
np.linspace(0,5 ,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [20]:
import numpy as np

arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

array3d= np.array([[[arr1[0], arr1[1], arr1[2]],
                            [arr2[0], arr2[1], arr2[2]]],
                           [[arr3[0], arr3[1], arr3[2]],
                            [arr4[0], arr4[1], arr4[2]]]])

print(array3d)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [40]:
print(type(array3d))
print(array3d.dtype)
print(array3d.shape)
print(array3d.size)
print(array3d.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [54]:
newarray=array3d.reshape(2,2,1,3)
newarray
print(newarray)
print(newarray.ndim)
print(newarray.shape)

[[[[ 1.1  2.1  3.1]]

  [[ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]]

  [[10.1 11.1 12.1]]]]
4
(2, 2, 1, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [200]:
newarray1=newarray.astype(int)
newarray1

array([[[[ 1,  2,  3]],

        [[ 4,  5,  6]]],


       [[[ 7,  8,  9]],

        [[10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [80]:
with np.nditer(newarray1) as it:
    for i in it:
        print(i)


1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [160]:
newarray1[1,0,0,1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [206]:
newarray1[ 0 , 1 , 0 , 1:3]

array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [218]:
print(np.where(newarray1==8))

(array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [221]:
newarray1.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [229]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

join_ar=np.concatenate((arr1 ,arr2), axis=0)

join_ar

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [231]:
join_ar=np.concatenate((arr1 ,arr2), axis=1)

join_ar

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [235]:
split_arr=np.split(join_ar , 2 , axis=1)
split_arr

[array([['A', 'B'],
        ['E', 'F']], dtype='<U1'),
 array([['C', 'D'],
        ['G', 'H']], dtype='<U1')]