In [13]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [37]:
x=np.ones((2,2)) #
x

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [43]:
y=np.zeros((2,2))
y

array([[0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [45]:
x+y

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [71]:
print(x.ndim)
print(x.shape)
print(x.size )
print(x.dtype )


2
(2, 2)
4
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [246]:
w=np.array([[11 ,13 ,15],[12,14,16]])
w

array([[11, 13, 15],
       [12, 14, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [159]:
z=np.array([[1],[2],[3]])
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".


In [234]:
newArray = np.hstack((z, w.T))  
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [168]:
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [179]:
newArray.transpose()

array([[-1,  0,  1],
       [ 9, 11, 13],
       [10, 12, 14]])

## Q#10: Decrement all elements of "newArray" with 1.

In [203]:
newArray-=1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [181]:
newArray.min()

-1

## Q#12: Print the first row of "newArray" using indexing.

In [205]:
newArray[0]

array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [207]:
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [226]:
print(newArray[0,0])
print(newArray[1,2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [228]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [244]:
newArray.reshape(3,3) #"The reshape method requires the number of elements to be equal. In this case, it is not valid because it needs fewer elements."

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

# Well Done 🎉